variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

# This template uses jdk8 for verifying and deploying images
image: maven:3.3.9-jdk-8

stages:
    - test
    - build
    - deploy
    - release

cache:
  paths:
    - .m2/repository

.verify: &verify
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
  except:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
verify:jdk8:
  <<: *verify

build:
    stage: build
    script:
        - 'mvn versions:set -DnewVersion=$CI_COMMIT_TAG'
        - 'mvn $MAVEN_CLI_OPTS clean package'
    only:
        - tags
    artifacts:
      paths:
        - target/$CI_PROJECT_NAME-$CI_COMMIT_TAG-jar-with-dependencies.jar

deploy:
    stage: deploy
    image: 
      name: minio/mc
      entrypoint: ['']
    only:
        - tags
    before_script:
        - mc alias set releases $MINIO_HOST $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
    script:
        - mc cp target/$CI_PROJECT_NAME-$CI_COMMIT_TAG-jar-with-dependencies.jar releases/plugins/$CI_PROJECT_NAME/$CI_PROJECT_NAME-$CI_COMMIT_TAG-jar-with-dependencies.jar

release:
  stage: release
  dependencies:
    - deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - release-cli create --name "$CI_COMMIT_TAG" --description "$CI_COMMIT_TAG" --tag-name "$CI_COMMIT_TAG" --ref "$CI_COMMIT_SHA" --assets-link "{\"name\":\"$CI_PROJECT_NAME-$CI_COMMIT_TAG-jar-with-dependencies.jar\",\"url\":\"$MINIO_HOST/plugins/$CI_PROJECT_NAME/$CI_PROJECT_NAME-$CI_COMMIT_TAG-jar-with-dependencies.jar\",\"link_type\":\"package\"}"
  only:
    - tags
