 # General Settings
general:

  #Should be either "SQLITE" OR "MYSQL"
  sync-mode: MYSQL

  #Wheather or not Whitelist Sync Should Sync Ops
  sync-ops: false

# Settings Related to the SQLite Database Sync Mode
sqlite:
  database-path: ./whitelist.db

  #Time in seconds for the service to check the filesystem listener for changes (ONLY WHEN IN INTERVAL MODE)
  sync-time: 60

# Settings Related to the MYSQL Database Sync Mode
mysql:
  #Name of the database
  database-name: whitelist

  #IP of the MYSQL Server
  ip: localhost

  #Port of the MYSQL Server
  port: 3306

  #Login Information (This SHOULD NOT be root) I am not responsible for your security issues ;)
  username: whitelist
  password: password

  #Time in seconds for the service to check the database for changes
  sync-time: 30
