name: WhitelistSync
version: 3.0.0
main: pw.twpi.whitelistsync.WhitelistSync

commands:
  wl:
    description: Command for whitelisting players and syncing the changes with connected servers.
    usage: /wl <list|add|remove|sync|copyServerToDatabase>

  wlop:
    description: Command for opping players and syncing the changes with connected servers.
    usage: /wlop <list|op|deop|sync|copyServerToDatabase>

permissions:
  whitelistsync.wl.view:
    description: Allows the user to view whitelisted players using the list command.
    default: false
  whitelistsync.wl.manage:
    description: Allows the user to update the whitelist using the add, remove, sync, and copyServerToDatabase commands.
    default: false
    children:
      whitelistsync.wl.view: true
  whitelistsync.wlop.view:
    description: Allows the user to view a list of opped players using the list command.
    default: false
  whitelistsync.wlop.manage:
    description: Allows the user to update the op list using the add, remove, sync, and copyServerToDatabase commands.
    default: false
    children:
      whitelistsync.wlop.view: true