name: WhitelistSync2
version: 1.18.1-2.2.4
main: pw.twpi.whitelistsync2.WhitelistSync2

commands:
  wl:
    description: Command for whitelisting players and syncing the changes with connected servers.
    usage: /wl <list|add|remove|sync|copyServerToDatabase>

  wlop:
    description: Command for opping players and syncing the changes with connected servers.
    usage: /wlop <list|op|deop|sync|copyServerToDatabase>

permissions:
  whitelistsync2.wl.view:
    description: Allows the user to view whitelisted players using the list command.
    default: op
  whitelistsync2.wl.manage:
    description: Allows the user to update the whitelist using the add, remove, sync, and copyServerToDatabase commands.
    default: op
    children:
      whitelistsync2.wl.view: true
  whitelistsync2.wlop.view:
    description: Allows the user to view a list of opped players using the list command.
    default: op
  whitelistsync2.wlop.manage:
    description: Allows the user to update the op list using the add, remove, sync, and copyServerToDatabase commands.
    default: op
    children:
      whitelistsync2.wlop.view: true